FROM python:3.8.10

RUN pip install Flask==2.2.0  
RUN pip install requests==2.22.0
RUN pip install matplotlib
RUN pip install numpy
RUN pip install redis==4.5.4
RUN pip install hotqueue==0.2.8

ADD ./auto_trends_data.csv /auto_trends_data.csv
ADD ./api.py /api.py

CMD ["python", "/api.py"]
